BBBBBBB BBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBB

BBBBB BBBBBBBBBB gettext(u'Confirm E-mail Address') BBBBBBBB


BBBBB BBBBBBBBBBBB
XXXX gettext(u'Confirm E-mail Address') XXXXX

BB BBBBBBBBBBBB

BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB

XXX gettext(u'Please confirm that <a href="mailto:%(email)s">%(email)s</a> is an e-mail address for user %(user_display)s.') SSSSSS SSSSSSS SSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS SS SSSSSS SSSSSSS SSS SSSS SSSSSSSSSSSSSSSSSXXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBXX
BBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXX gettext(u'Confirm') XXXXXXXXX
XXXXXXX

BBBB

BBB BBBBBBBBBBBBBBB BB BBBBBBBBB

XXX gettext(u'This e-mail confirmation link expired or is invalid. Please <a href="%(email_url)s">issue a new e-mail confirmation request</a>.') SSSS SSSSSS SSSSSSSSSSSS SSSS SSSSSSS SS SS SSSSSSSS SSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSS S SSS SSSSSS SSSSSSSSSSSS SSSSSSSSSSSSXXXX

BBBBB

BBBBBBBB