BBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBXXX XXBBBBBBBB
BBBBB BBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXX XXXXXXXXXX
        BBBBBBBBBB
        FFFFFF
        XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX
    XXXXXXX
BBBBBBBB