BBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBB
    XXXX XX
BBBBBBBB
BBBBB BBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXX XXXXXXXXXX
        BBBBBBBBBB
        FFFFFF
        XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX
    XXXXXXX
BBBBBBBB
